#!/usr/bin/env ruby

require File.dirname(__FILE__) + '/markd'

TR = [[/\r\n/m, "\n"],
      [/\n\n\n+/m, "\n\n"],
      [/(\n|^)([^\n]{1,80})\n([^\s]{1,80})/m, nil, :splitmore],
      [/(\n|^)([^.\s][^\n]+)\n(\s+[-\*\d])/m, "\\1\\2\n\n\\3"],
      [/\n\n\n+/m, "\n\n"]]

def splitmore(fullmatch, m)
  rval = fullmatch
  gap = 79 - m[2].length
  rval =  m[1]+m[2]+"\n\n"+m[3] if gap > m[3].length
  return rval
end

converge do |txt|
  txt.apply_transforms TR
end
